### ISSUE TITLE
UTF-8 codec can't decode byte

### ISSUE THREAD

**Issue by squishybanana04** [Roche/pyreadstat#18]
I'm getting this error when I try to `read_xport` on a sas file:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 3: invalid start byte
```
It's weird because pandas is able to load the file. I'm only using pyreadstat to get the column labels.

**Comment by ofajardo** [comment]
This means you have non-ascii characters in your file. Pandas and pyreadstat follow different strategies here. Pandas gives you raw bytes for the user to interpret them. Pyreadstat attempts to convert to string. In your case it can't and the error comes. That may be because the file is malformed, or because there is a bug in Readstat. A workaround is using pyreadstat with python 2.7 (not working on windows) because there strings are actually bytes while in python 3 strings are unicode.
I cannot say more because you are not providing enough information to look at the Error. You need to provide everything to be able to reproduce the error: system if your computer, python version, full stacktrace and a file that produces the error. Without all of this it's impossible to look into it.

**Comment by squishybanana04** [comment]
I've attached my data file, and here is my python version
```
python
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda custom (64-bit) on darwin
```
[2001-2002.L28POC_B.XPT.gz](https://github.com/Roche/pyreadstat/files/2848634/2001-2002.L28POC_B.XPT.gz)

**Comment by ofajardo** [comment]
ok thanks! I can reproduce the issue. I will take a look.

**Comment by ofajardo** [comment]
It seems to be a bug in the C library Readstat (the one pyreadstat is wrapping). I have filed a issue over there, to see if they can solve it. You can read more details on that [issue](https://github.com/WizardMac/ReadStat/issues/172) if you are interested. Thanks for reporting

**Comment by ofajardo** [comment]
It is now corrected on the dev branch. It will take a while until it reaches pypi and conda, but if you are in a hurry you can build it from there. 

If you do it is necessary to pass the encoding manually:

```
import pyreadstat
df, meta = pyreadstat.read_xport("2001-2002.L28POC_B.XPT", encoding="WINDOWS-1252")
```

**Comment by squishybanana04** [comment]
I still get the error. Here is what I did
```
$ git clone --recursive https://github.com/Roche/pyreadstat.git
Cloning into 'pyreadstat'...
remote: Enumerating objects: 661, done.
remote: Total 661 (delta 0), reused 0 (delta 0), pack-reused 661
Receiving objects: 100% (661/661), 19.89 MiB | 10.79 MiB/s, done.
Resolving deltas: 100% (335/335), done.
$ cd pyreadstat/
$ git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
$ python setup.py install
...
```
It still gives me the same error.

**Comment by ofajardo** [comment]
strange ... it works for me ... and did you specified the encoding? that's essential otherwise you get the same error. The other thing, make sure that you are importing the newly installed one and not an old version ...

**Comment by squishybanana04** [comment]
I'm using anaconda to import the library. The line I use to read the database is here
```python
reader, meta = pyreadstat.read_xport(filename, metadataonly=True, encoding="WINDOWS-1252")
```

**Comment by squishybanana04** [comment]
Oh nevermind, the error is because I'm on a mac and it's trying to import .DS_Store (my fault)

**Comment by squishybanana04** [comment]
Thanks for the help!

**Comment by ofajardo** [comment]
happy to help! Just one question out of curiosity: you say you read the data itself with pandas and use pyreadstat only for the metadata. What is precluding you from using pyreadstat for reading the data as well, or in which way is pandas more appropriate for your task?

**Comment by squishybanana04** [comment]
I have almost 5000 (or something like that don't remember the actual number) XPT files downloaded from [NHANES](https://wwwn.cdc.gov/nchs/nhanes/default.aspx) that I am trying to join into one csv file on a column. I probably could use pyreadstat for the whole thing but I thought it would be easier to use pandas for the join. I'm just using pyreadstat to generate documentation from the column labels.

**Comment by ofajardo** [comment]
Fair enough. However the joining would always happen in pandas: both in pandas and pyreadstat you have to first read each file and then join the pandas dataframes. Difference would be speed pyreadstat being normally faster.
Pyreadstat gives back a perfectly normal pandas dataframe you can join. 
Unless pandas allows you to pass the paths for all files and it reads and joins them on the fly ... If it can do that, yes that would be easier (can it?)

**Comment by squishybanana04** [comment]
Oh I didn't realize that pyreadstat would give a pandas dataframe. I'm gonna try rewriting my code now because it was waay too slow.
